### ISSUE TITLE
SSL certfile stops being read after 15th connection

### ISSUE THREAD

**Issue by christophermlewis** [pma/amqp#108]
Hi folks,

can anyone help, we are getting the following error when we make the 16th SSL AMQP connection.

** (MatchError) no match of right hand side value: {:error, {:options, {:keyfile, '../../certs/devbox.key.pem', {:error, :enoent}}}}

The connection looks like this:  
  AMQP.Connection.open("amqps://xxx:xxx@localhost:5671?keyfile=../../certs/devbox.key.pem&certfile=../../certs/devbox.crt.pem&cacertfile=../../certs/cacert.pem&verify=verify_peer&fail_if_no_peer_cert=true&server_name_indication=disable") end)

Subsequent attempts to connect fail in the same way.
It appears that it is isolated to the node that is running as I can connect with the same connection url in another iex session.
Any ideas, is there a node limit of some sort? 

Danke!

**Comment by pma** [comment]
@christophermlewis `enoent` indicates a missing file or directory. Are you sure those relative paths point to existing paths in the executing node? Or since you're using relative paths, maybe the process current dir is not what you think it is? You could try using absolute paths just to discard or confirm this possibility.

**Comment by christophermlewis** [comment]
fair point, the file does exist, but I'll set absolute paths and confirm

**Comment by christophermlewis** [comment]
yep you were right, path must be getting flipped as full path all is good. 
Good spot, thank you ;)
