### ISSUE TITLE
Bad config for the 'stable RabbitMQ connection' example

### ISSUE THREAD

**Issue by Qqwy** [pma/amqp#116]
When you'd use the code as listed in the [Stable RabbitMQ connection example](https://github.com/pma/amqp#stable-rabbitmq-connection), and you try to run this process as part of your main app's supervision tree, then you will lock your supervision up until the connection can be established during app startup, since `init` is run in the _caller_ rather than in the started GenServer!

Instead, use `send(self(), :setup)` from `init`, and add a `handle_info` clause that uses this message (which will be the first in the inbox since no other process will have been able to get hold of the GenServer's PID yet) to call `rabbitmq_connect()`.

**Comment by ono** [comment]
Good point.

I think it's probably best moving the sample code from README to `/examples` or somewhere. We should rewrite it for the production use or at least put some comments. Same can apply to the reconnection sample code too.

**Comment by aquarhead** [comment]
Speaking of "stable RabbitMQ connection", there are more situations to consider, especially when connecting to a RabbitMQ cluster instead of a single node.

I wrote about this here: https://blog.aquarhead.me/2018/07/stable_rabbitmq and example code is here: https://github.com/aquarhead/musical-octo-happiness/blob/master/lib/test_durable_queue/tester.ex

I have been since running slight variations of this example code in production applications and they're pretty stable regardless of various issues we had on our RabbitMQ clusters.

**Comment by ono** [comment]
Updated README. Thanks!
