### ISSUE TITLE
Failed Publish Returns `:ok` but the channel is killed

### ISSUE THREAD

**Issue by mmmries** [pma/amqp#15]
This might be intended behavior, but I'm trying to understand how I should handle this in my application code.

### To Reproduce

```elixir
{:ok, conn} = AMQP.Connection.open("amqp://guest:guest@localhost")
{:ok, chann} = AMQP.Channel.open(conn)
AMQP.Confirm.select(chann) # => :ok
AMQP.Basic.publish chann, "non-existent-exchange", "routing.key", "ohai" # => returns :ok
AMQP.Confirm.wait_for_confirms(chann)
```

The call to `wait_for_confirms` raises an error like:
```
** (exit) exited in: :gen_server.call(#PID<0.1275.0>, {:wait_for_confirms, :infinity}, :infinity)
    ** (EXIT) no process
         (stdlib) gen_server.erl:212: :gen_server.call/3
    (amqp_client) src/amqp_channel.erl:239: :amqp_channel.wait_for_confirms/2
```

### The Request

Ideally if I'm specifically waiting for publisher confims it would be awesome if I could get back an error message for my `AMQP.Confirm.wait_for_confirms` call. Something I can pattern match on, rather than trying to catch an error.

I'm happy to help out with development on this if it is a use-case you want to handle in this library.

**Comment by pma** [comment]
@mmmries The issue is not specific to `wait_for_confirms`. The channel process dies (silently) after the failed publish, so any `:gen_server.call` to the same channel process will give the same "no process" error.

One way to handle this is to always declare the exchange before you publish to it. Or you can have a local function that wraps publish and wait_for_confirms in a try catch.
