### ISSUE TITLE
AMQP.Queue.subscribe

### ISSUE THREAD

**Issue by triptec** [pma/amqp#16]
Hello, if I make the function I pass raise a exception, there's a reraise exception, stacktrace in do_consume that terminates the process and it stops processing messages. I'd like it not to reraise is there a good reason for the reraise?

**Comment by pma** [comment]
@triptec The catch is used to Basic.reject the message so it doesn't hang unacked in the broker when the consumer dies, not to hide the exception. That's why it's reraised.

But I didn't find much use for the Queue.subscribe convenience function outside simple escripts. I'd recommend using the OTP approach and setup a GenServer consumer as described in the 2nd example of the README. You have much more control and it will have better failure handling under a supervision tree.

**Comment by triptec** [comment]
Yes, I've ended up using that example and added a Process.link to the conn pid so that the whole thing goes down and can be restarted if the connection fails.

I'm wondering if there's a possibility to make a more generic Consumer that's a part of AMQP that one could use with "use Consumer" that only would have a user implement a consume function or possibily just pass the Consumer  connection, queue, exchange, routing_key info and a message handler so that there is a Consumer implemented with best practices that a new guy like me can use or look at when I implement my own.
I'd probably also like to have a generic Producer that one could pass conn, exchange and a name so that we later just can use send(:name, {:publish, message}) or something similar, more or less I would like to not have to think about connection handling. Or should what I'm talking about be a lib building on this to make it simpler?

**Comment by pma** [comment]
@triptec A Consumer behaviour that is a superset of GenServer makes sense. It could also serve the purpose of removing the mediation process that currently just transforms the record sent by the Erlang client.

This is a branch with a previous experiment: https://github.com/pma/amqp/blob/pma_consumer_behaviour/lib/amqp/consumer.ex

Feel free to experiment and send a PR to the master branch.

Regarding more higher level functions, I think we could build something else on top of the basic amqp client. In the .Net world I've used MassTransit (https://masstransit.readthedocs.org/en/latest/). It implements the ServiceBus pattern and takes care of message serialization, connection pooling, convention based declaration of Exchanges and bindings. This could be generic enough to plug other  transports besides amqp.

**Comment by triptec** [comment]
I looked at your experiment and I think I might not be ready to dive into Behaviours ;)

Something like MassTransit would be to big of a scope for me I think.

Coming from ruby I love bunny (http://rubybunny.info/articles/getting_started.html) and I think that might be something I could start trying to implement on top of amqp just to get a running start and work on the interface and when that's all nice maybe change to the amqp_client.

I'm wondering what would be a nice interface though..
Lib.Consumer(opts, fn (payload, _meta) -> ... end)
Lib.Producer(opts, name)
Lib.Producer.publish(name, %{payload: "payload", queue: "some queue"})

**Comment by pma** [comment]
@triptec Took at quick look at the bunny API. It's actually not too different from the Exlir amqp lib. The difference is due to the functional vs OO paradigm. 

In bunny we can have `x.publish("Hello!", :routing_key => q.name)`, where x is an exchange, because it's an object and holds the channel/connection. In Elixir we need to pass the channel around because it keeps the process holding the connection.

I'm not a fan of the callback function in the consumer API. The OTP approach where a Consumer is a GenServer that can be under a Supervisor makes error recovery much simpler. What would be the recovery strategy in case of failure with the callback approach? Where can we trap the error so we can do something about it?

Regarding MassTransit, some ideas I find useful are:
 * Connection recovery: If the TCP connection to the broker is lost, the client will retry until success and then recreate all subscriptions. The Java RabbitMQ client actually has this, so maybe it belongs the the client and not in a layer above it.
 * Message serialization: define how the payload is serialized instead of using an API that expects a binary payload
 * Implement some patterns like pub-sub and map to Exchange/binding concepts using some convention. For example, doing Bus.subscribe(%UserUpdated{}, "my-queue") on the Consumer would take care of creating Exchanges, bindings and queues. Then we can do Bus.publish(%UserUpdated{id: 1, active: false}) on the Producer side.

**Comment by triptec** [comment]
This is how I might use it, don't think the code works now but it might show my intent:
https://gist.github.com/triptec/f5a40543cf97ba7ec616

**Comment by triptec** [comment]
Most of it is more or less copied from the examples you got and added Process.link to the conn pid

**Comment by triptec** [comment]
I've been thinking for a while and the gist mostly doesn't make sense.
Anyways, thanks for your time!
