### ISSUE TITLE
Callback implementations for testing

### ISSUE THREAD

**Issue by joeyrosztoczy** [pma/amqp#162]
Hi! I was curious what your thoughts were on providing callbacks in the library to help applications using the library to mock responses (for example with Mox or flipping modules to custom responses during test).

We recently used amqp as our client for rabbit (its awesome so major thanks and kudos). However, we ended up doing a custom callback implementation that it occurred to me many users could benefit from.

If you guys were open to the idea, I'd be happy to contribute a PR!

A few thoughts on what this would look like for end users -

with Mox:

```elixir
# In test_helper.exs
Mox.defmock(AMQPConnectionMock, for: AMQP.Connection)
    
# In test
expect(AMQPConnectionMock, :open, fn _ ->
  {:error, nil}
end)
```
No dependency:

```elixir
defmodule AMQP.ConnectionMock do
  alias AMQP.Connection

  @callback open(keyword | String.t()) ::
              {:ok, %Connection{}} | {:error, atom()} | {:error, any()}

  def open(_options_or_uri) do
    {:ok, connection_pid} = Agent.start_link(fn -> %{} end)
    {:ok, %Connection{pid: connection_pid}}
  end
end
```

**Comment by whatyouhide** [comment]
I will add my opinion, even if I don't maintain this library. I think having an interface for this *in your codebase* is beneficial to your application's architecture since you're not tying yourself to a library, but you're being explicit on *how* you use the external dependency (RabbitMQ) instead. For example, in one of our services at work we have:

```elixir
defmodule MyApp.AMQP do
  @type connection() :: AMQP.Connection.t()
  @type channel() :: AMQP.Channel.t()

  @callback open_connection(uri :: String.t()) :: {:ok, connection()} | {:error, term()}
  @callback open_channel(connection()) :: {:ok, channel()} | {:error, term()}
  @callback select_confirms_and_register_handler(channel(), pid()) :: :ok | {:error, term()}
  @callback next_confirm_seqno(channel()) :: non_neg_integer()
  @callback publish_message(
              channel(),
              exchange :: String.t(),
              routing_key :: String.t(),
              payload :: binary(),
              options :: keyword()
            ) :: :ok | {:error, term()}

  def open_connection(uri), do: AMQP.Connection.open(uri)

  def open_channel(connection), do: AMQP.Channel.open(connection)

  def select_confirms_and_register_handler(channel, pid) do
    with :ok <- AMQP.Confirm.select(channel) do
      :ok = AMQP.Confirm.register_handler(channel, pid)
    end
  end

  def next_confirm_seqno(channel), do: AMQP.Confirm.next_publish_seqno(channel)

  def publish_message(channel, exchange, routing_key, payload, options) do
    AMQP.Basic.publish(channel, exchange, routing_key, payload, options)
  end
end
```

I really straight copied it out our codebase but the idea is that as you can see some operations are bundled together and the interface we define is the interface that our application needs to talk to RabbitMQ. Hopefully that makes sense. :)

**Comment by joeyrosztoczy** [comment]
@whatyouhide that's very similar to our interface. I definitely agree that defining an interface in an application is the cleanest way to go.

It might also be worth adding an example to the README (I'd also be happy to contribute that via PR).

However, I can't help but think that a callback implementation in the library is not mutually exclusive to defining an interface in the application.

I can see two benefits:

1. Reduced test friction (especially for side projects or projects that don't think to wrap). I think that's a worthwhile trade off in and of itself. We spent a couple hours prior to wrapping the implementation exploring other patterns, and there's a wide slew of projects implementing this client that don't test at all, or the tests only work with a full integration setup (locally running rabbit for example). 

2. A base implementation that eases friction for defining the interface in-app.

**Comment by ono** [comment]
IMO, Behaviour should be defined with a clear need on abstracting the interface. For example, if we need several implementations for `AMQP::Connection` such as different version etc., this library will abstract the interface with Behaviour.

The mock is required on application layer therefore the contract should be defined in application layer. The library shouldn't **guess** the contract/abstraction requiring on the upper layer.

I am aware that some libraries provide Behaviour mainly for mox and it can be useful for many situations. Therefore I can understand your motivation here but I hesitate to apply the practice to this library because of the reason above. At the same time, I like to keep this library as concise as possible.

Regarding the documentation, I personally think that it's more like a practice/knowledge to be shared by a blog post or discussed in Elixir forum. I believe that it can help more people who have similar questions with other libraries.

Thanks!

**Comment by ono** [comment]
By the way, in general, I personally recommend everyone starting your tests without mocking RabbitMQ. Like you connect to database in your tests, I highly recommend you to connect to actual RabbitMQ. I'd write a helper to set up - seed queues, exchanges or clean them - as needed. (it'll be an interesting topic how you can safely run tests in parallel)

Of course, I am not against mocking if you see actual needs for that though.

**Comment by joeyrosztoczy** [comment]
Absolutely agree! Its all dockerized so we can qa / verify as we go. The mocks are really helpful for isolating the app under specific conditions, like dropped connection, network partitions, etc prior to (or separate from) integration testing and qa.
