### ISSUE TITLE
AMQP.Basic.publish uses cast

### ISSUE THREAD

**Issue by edgurgel** [pma/amqp#20]
I was checking the `publish` function and noticed that it uses 

`:amqp_channel.cast`

https://github.com/pma/amqp/blob/master/lib/amqp/basic.ex#L73

Is there any reason why it's not a `:amqp_channel.call`? 

I would like to be sure that a message got sent properly to the channel and just casting I can't be sure that the channel received such message. 

Would it be desirable to accept an option to perform a call?

**Comment by pma** [comment]
@edgurgel Take a look at publisher acks (https://www.rabbitmq.com/confirms.html). I believe this is what you want. I've only seen `:amqp_channel.call` being used for publishing messages in the Erlang client docs.

With the Elixir wrapper you can do:

```
use AMQP
...
Confirm.select(chan)  # Do this once after opening the channel
...
:ok = Basic.publish(chan, exchange, routing_key, payload, meta)
Confirm.wait_for_confirms_or_die(chan)  # This will block and raise if no publish ack is received from the broker 
```

**Comment by edgurgel** [comment]
I'm not looking for confirms but just knowing that the channel process received the message from the process that sent the message. For my specific case would prefer to time out and fail here if the channel didn't receive it. 

I'm fine if this should not be available from the lib. I can close the issue and build the amqp message using `amqp_channel.call` directly.

Thanks for the library btw :+1:

**Comment by pma** [comment]
@edgurgel It's a local a local process, so it won't receive the cast only if it dies, correct? You could instead have the sender process monitor the channel to handle this case. 

Knowing that the channel pid received the message is no guarantee that the message won't be lost. Communication between the channel process and the broker is still async (see section Sending Messages in https://www.rabbitmq.com/erlang-client-user-guide.html). With a call instead of cast, the channel process may receive the basic_publish command and reply `:ok` to the sender. But then the async communication with the broker fails and the message is still lost.

**Comment by edgurgel** [comment]
Yeah I understand that there are multiple places where this could fail but doing this would give a "back pressure" so the channel would need to acknowledge and reply back instead of "losing" a burst of messages that were sent to the channel. 

I will use `:amqp_channel.call` directly to achieve this. 

Thanks for your feedback.

**Comment by dantswain** [comment]
@edgurgel @pma FWIW I have run into the same issue.  In our case we have fairly high throughput and the channel process mailbox's `rabbit_writer` process backs up.

This is a somewhat dangerous situation because it does not have any directly observable effects (memory goes up, the downstream queue stops receiving data) and if the channel crashes while those messages are sitting in a mailbox, then those messages are lost forever.  The risk is compounded by the fact that this will probably not cause an actual crash until the systems starts to run out of memory, in which case there could be tens of thousands of messages or more lost in process mailboxes.  We have been working around it by monitoring process mailboxes and applying backpressure upstream if there is a mailbox backup.  Unfortunately once that process starts to get overwhelmed, it can take quite a while for the backup to clear.

I understand that Confirm is probably the "right" way to ensure that the messages go through, but IIUC it would be a bit of a hit to performance.  Using `:amqp_channel.call` is kind of a middle ground because it should be more performant (no network round trip for the confirm) and reduce the risk of losing messages (or at least reduce the number messages that could be lost).  I respect the decision not to change from `:cast` but it may be reasonable for this to be an option or at least for it to be documented?

**Comment by pma** [comment]
@dantswain `:amqp_channel.cast` is the interface exposed by the Erlang client. You can't send a basic_publish() record via `:amqp_channel.call`.

Publisher allow you to ensure the message was well received by the broker. You can avoid a performance hit if instead of blocking until a confirm is received, for every message, instead you register a handler to process the publish confirms you'll receive asynchronously.

amqp does not expose the handler registration, so you'll have to call `:amqp_channel.register_confirm_handler/2` directly.

In https://github.com/pma/wabbit/blob/master/lib/wabbit/gen_stage.ex#L441 I implemented this pattern.

**Comment by dantswain** [comment]
@pma I'm confused by this:

> :amqp_channel.cast is the interface exposed by the Erlang client. You can't send a basic_publish() record via :amqp_channel.call

The implementation of `amqp_channel` appears to be indifferent about whether call or cast is used - https://github.com/rabbitmq/rabbitmq-erlang-client/blob/master/src/amqp_channel.erl

I also just now implemented a version of `publish` that uses `:amqp_channel.call` instead of `cast` by copy/pasting from the AMQP implementation and replacing `cast` with `call`, and it appears to work just fine (as well as solving my underlying problem).

**Comment by pma** [comment]
@dantswain Thanks for pointing my mistake. The Erlang docs clearly state that in case of async methods, like publish, `:amqp_channel.call` can be used. The return will just mean that the request was transmitted to the broker, but not necessarily received and processed.

Now I don't see a reason why this shouldn't be the default in Basic.publish. If you're kind enough to send a PR I'll gladly merge it.

**Comment by dantswain** [comment]
@pma No problem, I was just worried I was missing something.

**Comment by dantswain** [comment]
@pma @ono Just wanted to say that #58 combined with using a publisher pool (using poolboy) solved our problem perfectly.  It has been in production about 12 hours and has definitely been an improvement.  Thanks again!  :tada:

**Comment by ono** [comment]
@dantswain that's great. thanks for the follow-up. it is always useful to know how changes have improved/affected in real situation 🙌
