### ISSUE TITLE
How would one approach having tests alongside this library?

### ISSUE THREAD

**Issue by Nikola-Milovic** [pma/amqp#216]
Hello, unfortunately, this isn't exactly an issue, but rather a discussion nevertheless, I am a bit lost. I have a supervisor that handles my connection, and then it supervises consumers. Since it all starts with the Application, I am unsure as to how to approach testing. As I don't wanna run rabbitmq instance while testing, and if I don't it crashes.  

My only idea is to have a behavior defined and a wrapper around the library and then snub it for testing. I am newish to Elixir so any pointers would be greatly appreciated.

This gets started with Application (ignore the fact that it might not work, I still haven't been able to test it)
```
defmodule Chat.AMQP.ConnectionManager do
  use Supervisor

  def start_link(opts \\ []) do
    GenServer.start_link(__MODULE__, :ok, name: __MODULE__)
  end

  def init(:ok) do
    children = [
      Chat.AMQP.ConsumerManager
    ]

    opts = [strategy: :one_for_one, name: Chat.AMQP.ConnectionManager]
    Supervisor.start_link(children, opts)
    establish_new_connection()
  end

  defp establish_new_connection() do
    case AMQP.Connection.open(connection_options()) do
      {:ok, conn} ->
        Process.link(conn.pid)
        {:ok, {conn, %{}}}

      {:error, reason} ->
        IO.puts("failed for #{inspect(reason)}")
        :timer.sleep(5000)
        establish_new_connection()
    end
  end

  def connection_options() do
    user = System.get_env("RABBITMQ_USER")
    password = System.get_env("RABBITMQ_PASSWORD")
    host = System.get_env("RABBITMQ_HOST")
    port = System.get_env("RABBITMQ_PORT")

    "amqp://#{user}:#{password}@#{host}:#{port}/"
  end

  def request_conn(consumer) do
    GenServer.cast(__MODULE__, {:conn_request, consumer})
  end

  def handle_cast({:conn_request, consumer}, {conn}) do
    consumer.connect(conn)

    {:noreply, {conn}}
  end
end
```

**Comment by whatyouhide** [comment]
There is no magic solution for something like this, and it's not quite an Elixir-specific problem. In these situations, you have a few options (spoiler alert: none of them are really great):

  * Run infrastructure alongside your application for testing. This is by far my preferred method. Yes, it's not ideal and you're not testing in isolation as much, but you'll want to exercise the actual code that connects to RabbitMQ at some point anyways, might as well do it as much as possible 😉 Luckily tools like Docker are just about fantastic for things like running infrastructure locally.
  * Conditionally add children to your supervision tree. For example, you can check if `Mix.env() == :test` and, if so, you can start the supervisor without any children. I don't generally recommend this since you'll probably have to spin up the app in the dev environment anyways to test its connection to RabbitMQ, but it solves your immediate issue.
  * You can use mocks, yes. The Elixir community generally uses [Mox](https://github.com/dashbitco/mox). Mox is pretty great at creating mocks of APIs based on behaviours, but in your case you'll have to tweak things around because the thing you want to create a mock for is really a whole process that you can start under a supervision tree.

Hope this helps somewhat 🙃

**Comment by Nikola-Milovic** [comment]
@whatyouhide  thank you for the response! Yeah, coming from some other languages to the Elixir, I was reluctant to run RabbitMQ alongside tests as it felt code smelly. But I opted for that option and it seems that was the right choice as I can keep the RabbitMQ container running, it doesn't affect the runtime of the tests, so all in all pretty decent solution.
