### ISSUE TITLE
Connection Recovery and Built-in Supervision Tree?

### ISSUE THREAD

**Issue by mmmries** [pma/amqp#22]
I'm starting up a project which needs to have some pretty solid rabbitmq support including failing over to another connection in the case of a network partition or a node dies in the rabbit cluster.

I would also like to have a standard supervision tree that I can just drop into an application and provide some configuration for which queues and bindings I would like to receive messages from and which functions should be called for those messages.

That way I don't have to re-invent the supervision tree and connection retry semantics on my own each time.

I have some [experience doing this in ruby](https://github.com/mxenabled/action_subscriber), and I see that [there is one potential solution](https://github.com/shopgun/turtle) in erlang, but I would rather invest my time into make this available to the hex.pm community.

Are these features things you would like to see in your project? Or should I start a separate project that builds on top of `amqp`/`amqp-client`?

**Comment by edgurgel** [comment]
I would check this project: https://github.com/shopgun/turtle

**Comment by pma** [comment]
@mmmries Hi. This is definitely something needed. I think the features would be worth it, even if the implementation introduces some breaking changes to the API. But if you decide to go with a separate project, I don't see much benefit depending on the amqp Elixir wrapper. Using the Erlang amqp_client library directly would be better. 

From a few failed attempts at implementing something along these lines I've come to realize it would force some breaking changes to the API. Some notes:

- The Connection must become a process that monitors the Erlang client connection pid, instead of a struct
- Same applies to the Channel
- A Connection starts one or more channels dedicated to publish and other control commands
- Introduce Broker, a process that manages a collection of Connections, possibly to different nodes of the RabbitMQ cluster
- The Broker pid handles the same messages as the Connection pid, so it can be 
- Control API receives the Broker pid instead of a Channel (declaring Exchanges/Queues etc.)
- The pattern to implement a Subscriber becomes:
   - A module that implements the Subscriber behaviour
   - init callback receives the Connection and is used to setup Exchanges, Bindings, etc.
   - other callbacks handle message delivery and other events from the broker
   - The subscriber is "registered" in a Connection, at the point where the Connection pid is start_link'ed
- The Connection restarts all consumers when it recovers after a disconnect

Edit: Thanks for the turtle link @edgurgel. Will take a look at it.

**Comment by mmmries** [comment]
@edgurgel turtle was what I was linking to when I mentioned an existing erlang option. I haven't used it enough to know if it will build cleanly as a [hex.pm](https://hex.pm) dependency. Do you think that project would be open to PRs to make it publishable via hex?

@pma in the meantime I need to learn about how things like backoff and reconnects should be handled in an OTP application anyway so I'll start trying to take a few small steps forward in this project.

**Comment by edgurgel** [comment]
@mmmries, I think they would push it to `hex.pm`. cc/ @jlouis

**Comment by jlouis** [comment]
We have an issue https://github.com/shopgun/turtle/issues/8 tracking hexification of `turtle` now.

As for the backoff/reconnect concept you should take a look at Fred's http://ferd.ca/it-s-about-the-guarantees.html which gives a good way of thinking about supervision in the setting of reconnects. In short, aim to always provide a process that is "there" and can answer there is no connection right now, and then run a reconnect loop inside the process. Backoff is most easily achieved by having a process high in the supervisor tree keep a history of reconnects. It can also implement policy. This lets lower-level workers in the tree ask it for the current state and do their work accordingly.

**Comment by mmmries** [comment]
I'm going to focus my efforts for now on getting `turtle` into `hex`. Thanks everyone for the help
