### ISSUE TITLE
Durable / Stable Connections

### ISSUE THREAD

**Issue by erez-rabih** [pma/amqp#25]
Hi,

I want to use the library to have a constant connection to the rabbitmq even if the server has a failure/drops. In that situation, I'd expect the client to have some kind of reconnect logic.

I am following the GenServer pattern offered in the README file with a supervisor, but if I drop the RabbitMQ server when the GenServer is running I get a :socket_closed_unexpectedly message and the client never tries to reconnect, even when the RabbitMQ goes up again. The supervisor does not try to start another client either (is it because we're returning the chan pid back to the supervision tree?)

Any suggestions to have a durable and stable connection to a rabbitmq server? Am I using the supervision tree / genserver pattern the wrong way?

Thanks for the help.

**Comment by pma** [comment]
@erez-rabih You can link your GenServer process to the connection pid with `Process.link(conn.pid)` after `{:ok, conn} = Connection.open`, to ensure it dies and can be restarted by your application supervisor. This is in part due to how the Erlang client handles keeps connection pids under it's own supervision tree: https://github.com/rabbitmq/rabbitmq-erlang-client/blob/master/src/amqp_connection.erl#L162.

You'll need to implement some kind of backoff mechanism, otherwise the supervisor will just quickly try to restart the genserver, hit the max_restarts of 5 and bring the entire application supervision tree down. You can reuse https://github.com/fishcakez/connection to implement the backoff mechanism.

Someone previously suggested using https://github.com/shopgun/turtle instead, which implements some common patterns, including automatic reconnects.

**Comment by erez-rabih** [comment]
@pma Thanks for the tips.

In the meantime, I used `Process.monitor` on the connection pid and I handle DOWN messages with reconnection + sleep delay in between retries.

It seems like a reasonable solution to me.

I'd be happy to submit a PR to the README if you'd like me to do so.

**Comment by pma** [comment]
@erez-rabih Thanks, a PR to improve the examples would be appreciated. The solution you describe appears to be the one used in https://github.com/mobileoverlord/fireworks/

**Comment by hubertlepicki** [comment]
@pma, @erez-rabih correct me if I'm wrong, but this example you pasted has some flaws. Most notably, it blocks while re-connecting. `GenServer` handles one message at a time, and when you do `:timer.sleep()` the `GenServer` that executes it becomes unresponsive to both - user-generated and system-generated messages.

Is there a reason why you use `:timer.sleep()` rather than `:timer.send_after()` that is not blocking?

The link pasted above, for the fireworks thing does just that: https://github.com/livehelpnow/fireworks/blob/master/lib/fireworks/connection.ex#L37

I can provide you with slightly better code example if you wish :)

**Comment by erez-rabih** [comment]
@hubertlepicki Sure I'm always glad to receive improvements. I'm not an Elixir expert so I might have missed that.

**Comment by pma** [comment]
@hubertlepicki Please do send a PR to improve the example. I can also suggest we use `:erlang.send_after` instead of `:timer.send_after`, as suggested in the Erlang efficiency guide (http://erlang.org/doc/efficiency_guide/commoncaveats.html#id2262042).

/cc @erez-rabih
