### ISSUE TITLE
Configuration via config.exs

### ISSUE THREAD

**Issue by Mehonoshin** [pma/amqp#37]
I wonder if we could configure AMQP connection credentials via standard elixir config.exs.
As I can see it is common practice, and this library should follow it.

I can start work on it and make a PR.

@pma, what do you think?

**Comment by dantswain** [comment]
IMHO this should only be done as a convenience and not considered standard practice.  In general, a user can have multiple broker connections to one or more clusters with multiple channels etc, and each one needs to be configured separately.  That configuration should live in the space of the user's application - i.e., `config :my_app, :amqp_config_for_business_thing1`, `config :my_app, :amqp_config_for_business_thing2`, etc - and the user turns that configuration into worker processes in their own supervision trees.

**Comment by ono** [comment]
I talked to @pma about this. We think it's the best for amqp to stay away from configuration. amqp should stay as a thin wrapper for amqp_client to keep its portability.

As @dantswain suggested, the extra configuration should stay in user's application or the richer library that wraps amqp. @pma is working on [wabbit](https://github.com/pma/wabbit) for the idea. [A library](https://github.com/shinyscorpion/task_bunny) I am currently working on also provides an extra layer for amqp connection (I am planning to release 0.1 within couple weeks). Publishing a new hex library by yourself might be an idea too.

Closing this issue because of the reason but let me know if you have any questions.

Thank you.
