### ISSUE TITLE
Documentation on Numeric Arguements to Queue.declare

### ISSUE THREAD

**Issue by peck** [pma/amqp#4]
Need documentation on how to pass numeric arguments to Queue.declare, for example:

Queue.declare(chan, @queue, arguments: [{"x-message-ttl", :number, 5000}])

I've tried :number, :num, :numeric, as well as tried passing as a string as in the Readme but no success.

Could this be documented in the readme?

**Comment by pma** [comment]
@peck You case use `arguments: [{"x-message-ttl", :long, 5000}]` or `arguments: [{"x-message-ttl", :signedint, 5000}]`

I have updated the README as you suggested to include info about arguments. It would be nice to have the info in the documentation of the actual functions, instead of the README, but I will leave that to another commit. A PR to improve the docs would also be appreciated :)

The reference used was the source of the Erlang client. Here https://github.com/jbrisbin/rabbit_common/blob/6d69ae4981b718e45a4159402858c0257b3fcf04/src/rabbit_framing_amqp_0_9_1.erl#L47 are the valid types and here https://github.com/jbrisbin/rabbit_common/blob/6d69ae4981b718e45a4159402858c0257b3fcf04/src/rabbit_amqqueue.erl#L467 the validations that check the argument names and types.
