### ISSUE TITLE
Connection not monitored

### ISSUE THREAD

**Issue by amencarini** [pma/amqp#56]
Hi,
More than an issue this is a question!

I was wondering why the `connection.pid` is not monitored. We had the GenServer dying on us because of a dropped heartbeat and couldn't understand what was happening until we read the comment in the source code.

If it's a matter of putting some time to harden the code against a missed heartbeat let me know, I'd be happy to help.

**Comment by ono** [comment]
Hey @amencarini.

Good question!
amqp's main aim is to provide a thin wrapper of Erlang rabbitmq client for Elixir. That keeps this library portable. Things like connection monitoring should be handled in upper layer(either your application or another richer library).

Hope it can answer your question. Let me know if it's not.

**Comment by amencarini** [comment]
Perfectly answered, thanks for that! I might open a PR to document this a bit better on the readme if that's ok?

**Comment by ono** [comment]
Cool. Maybe we can rename "Troubleshooting" section to "FAQ and Troubleshooting" on README and add the topic there?

**Comment by amencarini** [comment]
Ok, I went to edit the "Stable RabbitMQ Connection" and just saw I missed the `Process.monitor(conn.pid)` that's already there. Sorry about this!

**Comment by Stratus3D** [comment]
Remember that `Process.monitor(con.pid)` alone will not be enough to calling process to get all the `:DOWN` messages from the connection process. This code, taken from the readme, allows the process to crash without the calling gen server ever getting a message:

```
case Connection.open("amqp://guest:guest@localhost") do
    {:ok, conn} ->
      # Get notifications when the connection goes down
      Process.monitor(conn.pid)
      ...
```

Since there is a delay between the process being spawned by `Connection.open/1` (`amqp_sup:start_connection_sup/1` is actually what spawns it) and the call to `Process.monitor(conn.pid)` it's possible the process will crash during that time. If it does the call to `Process.monitor/1` will still succeed and the caller will have no idea the process is actually already dead.
