### ISSUE TITLE
exeption in Queue.subscribe

### ISSUE THREAD

**Issue by mlankenau** [pma/amqp#57]
Hi there,

I have an issue with the subscribe function. i understand that raising an exception is rejecting the msg. Otherwise the msg will be 'acked'. But in case of an exception https://github.com/pma/amqp/blob/master/lib/amqp/queue.ex#L154 will re-raise and so subscribe will quit. Is that intended? I was expecting that it will continue receiving messages.

BR
Marcus

**Comment by pma** [comment]
@mlankenau Hi,

If we needed to ensure messages were processed in order, skipping in case of an exception in the handler for a single message wouldn't be an option, so I think it's valid to reraise and stop consuming.

To have more control in how failures are handled, I suggest implementing a GenServer consumer instead of using the convenience function Queue.subscribe. The Readme has an implementation example.

If you need a higher level abstraction, you may also want to give https://github.com/pma/wabbit a try.

**Comment by mlankenau** [comment]
we've wrapped the amqp stuff into a DSL (https://github.com/mlankenau/amqp_dsl) to keep our code free of all those implementation details. So I duplicated your subscribe code which is ok for me. For me it is important to keep listening even when an exception happened.
BR
