### ISSUE TITLE
Upgrading amqp to work with latest 3.7.1 amqp_client and rabbit_common

### ISSUE THREAD

**Issue by carl-al** [pma/amqp#84]
```elixir
@tag :skip_ci
  # This test assumes that we have a running RabbitMQ with short
  # nodename 'rabbit@localhost', and that it uses the same Erlang
  # cookie as we do. And it's better to have RabbitMQ of version
  # equal to that of amqp_client library used. We can achieve this
  # with following sequence of commands under the same user that
  # will run the test-suite:
  #
  # wget https://github.com/rabbitmq/rabbitmq-server/releases/download/rabbitmq_v3_6_9/rabbitmq-server-generic-unix-3.6.9.tar.xz
  # tar xJvf rabbitmq-server-generic-unix-3.6.9.tar.xz
  # cd rabbitmq_server-3.6.9
  # RABBITMQ_NODENAME=rabbit@localhost ./sbin/rabbitmq-server
  test "open direct connection" do
    :ok = ensure_distribution()
    assert {:ok, conn} = Connection.open_direct node: :rabbit@localhost
    assert :ok = Connection.close(conn)
  end
```
Why does this test exist?  I cannot make it work and is not a very good test, why not setup the environement before the test runs?

Anyway searching for clarification, and want to understand why it is ignored anyway.
Should this be removed?

**Comment by Ayanda-D** [comment]
its a sanity test for https://github.com/pma/amqp/pull/61 - which assumes you have `rabbit@localhost` running on your local machine

**Comment by ono** [comment]
Also it currently has a problem on rabbitmq_client.

- https://github.com/pma/amqp/issues/73
- https://github.com/rabbitmq/rabbitmq-erlang-client/issues/91

The rabbitmq_client team seems to look for a support. If anyone can sort it out it will be great.

**Comment by carl-al** [comment]
@Ayanda-D the test does not work. Simple. Ignoring it does not make it go away. The readme should be updated to supply informational or sanity based requirements.

As for the feature itself, it is not working even after I have followed what is in the comments. 
FYI the test itself can be set-up or mocked.

Again not clear on whats going on there so cannot at this stage fix it

**Comment by ono** [comment]
I don't see any issue with test itself. It's meaningful to connect actual RabbitMQ server on the test. Unfortunately it requires some configuration and doesn't work on Travis CI but it is still useful to have.

As I mentioned above the problem is https://github.com/rabbitmq/rabbitmq-erlang-client/issues/91 . It is filed on our issue #73 too. You would find the issue by searching open_direct with github issues. Beside, without having the test, I wouldn't notice the issue.

I expected that it would be fixed more quickly on amqp_client. However it is not sorted. For time being, I removed `open_direct/1` on master. We will be adding it again when it's sorted.
